name: CI

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.16.3'
      - name: Install dependencies
        run: npm install

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install Pipenv
        run: pip install pipenv
      - name: Setup stage
        if: endsWith(github.ref, 'develop')
        run: echo ::set-env name=STAGE::dev
      - name: Setup stage2
        if: endsWith(github.ref, 'master')
        run: echo ::set-env name=STAGE::prod
      - name: Build
        run: node_modules/.bin/sls deploy -v --stage ${STAGE}
        env:
          AWS_DEFAULT_REGION: ap-northeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLACK_WEBHOOK_URL:  ${{ secrets.SLACK_WEBHOOK_URL }}
